// <auto-generated />
namespace OCTA_Projet_Gestion_Commerciale.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class yareb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yareb2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808262045029_yareb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
